services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      DATABASE_URL: sqlite:////app/db/fitness.db
      JWT_SECRET_KEY: dev-secret
    volumes:
      - backend-db:/app/db
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    ports:
      - "8080:80"

volumes:
  backend-db:
