services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      DATABASE_URL: sqlite:///fitness.db
      JWT_SECRET_KEY: dev-secret
#    volumes:
#      - backend-db:/app/fitness.db
    expose:
      - "5000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "8080:80"

volumes:
  backend-db:
