services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - .env
    environment:
      DATABASE_URL: sqlite:////app/db/fitness.db
      JWT_SECRET_KEY: ${JWT_SECRET_KEY:-dev-secret}

      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID:-}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET:-}
      GOOGLE_REDIRECT_URI: ${GOOGLE_REDIRECT_URI:-http://localhost:5000/api/auth/google/callback}
      FRONTEND_OAUTH_REDIRECT: ${FRONTEND_OAUTH_REDIRECT:-http://localhost:8080/login/oauth}

      CORS_ORIGINS: ${CORS_ORIGINS:-http://localhost:8080}
    volumes:
      - backend-db:/app/db
    ports:
      - "5000:5000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    ports:
      - "8080:80"
    restart: unless-stopped

volumes:
  backend-db:
