name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install project (editable) + dev tools
        run: |
          python -m pip install --upgrade pip
          # instalacja całego repo w trybie editable – daje import backend
          pip install -e .[dev]      # jeśli masz extras "dev"
          # jeśli nie używasz extrasów, wystarczy:  pip install -e .

      # Ruff z poziomu katalogu głównego – sprawdzi cały kod
      - name: Run Ruff (lint)
        run: ruff check .

      # Pytest z poziomu głównego – znajdzie backend/tests
      - name: Run Pytest
        run: pytest --maxfail=1 --disable-warnings -q --cov=.

  build-containers:
    needs: lint-and-test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check Docker version
        run: docker --version

      - name: Build Docker Compose images
        run: docker compose build
